# Generated by Django 5.1.6 on 2025-02-06 18:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Kitap',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('yazar', models.CharField(max_length=255)),
                ('isim', models.TextField(blank=True, null=True)),
                ('yaratilma_tarihi', models.DateTimeField(auto_now_add=True)),
                ('güncellenme_tarihi', models.DateTimeField(auto_now=True)),
                ('yayin_tarihi', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Yorum',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('yorum_sahibi', models.CharField(max_length=255)),
                ('yorum', models.TextField(blank=True, null=True)),
                ('yaratilma_tarihi', models.DateTimeField(auto_now_add=True)),
                ('güncellenme_tarihi', models.DateTimeField(auto_now=True)),
                ('kitap', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='yorumlar', to='kitaplar.kitap')),
            ],
        ),
    ]
