# Generated by Django 5.1.6 on 2025-02-06 18:46

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kitaplar', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='kitap',
            name='aciklama',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='yorum',
            name='degerlendirme',
            field=models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)]),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='kitap',
            name='isim',
            field=models.CharField(default=2, max_length=255),
            preserve_default=False,
        ),
    ]
